version: '3'
services:
  web:
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/colaboradores
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file: .env
  redis:
    image: redis:5.0.7
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle exec sidekiq -q default -q mailers"
    depends_on:
      - web      
      - redis
    volumes:
      - .:/app
    env_file: .env
